#!/bin/sh
#
# Input JSON from STDIN
# {
#   "source": {
#     "bucket": "test",
#     "bucket_subfolder": "subfoo/",
#     "filter": "zip",
#     "aws_access_key_id": "xxxx",
#     "aws_secret_access_key": "yyy",
#     "aws_default_region": "us-east-1",
#   },
#   "version": { "ref": "file.zip" }
# }

set -e
IFS=" "

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

{ # Hide all output

source $(dirname $0)/common.sh

parse_source_config

DESTINATION_DIR=$1

cd $DESTINATION_DIR

KEY=$(aws s3 ls s3://${BUCKET}/${BUCKET_DIR%/}/ --recursive | grep .json | grep "${VERSION}" | sort | tail -n 1 | awk '{print $4}')

aws s3 cp s3://$BUCKET/$KEY ./
               
FILE=$(ls *.json)

REMOTE=$(cat ${FILE} | jq -r .remote)
COMMIT=$(cat ${FILE} | jq -r .commit_sha)
TRIGGER=$(cat ${FILE} | jq -r .trigger)
METADATA=$(cat ${FILE} | jq -r .metadata)
# Checkout the commit
# TODO: Implement private repos and all (like this one: https://github.com/concourse/git-resource/blob/master/assets/in)
git clone --bare "https://github.com/${REMOTE}" .git
git config --unset core.bare
git remote rm origin
git remote add origin "https://github.com/${REMOTE}"
git reset --hard ${COMMIT}
mkdir .git/resource
echo "${COMMIT}" > .git/resource/ref
echo "${VERSION}" > .git/resource/version

} > /dev/null


cat >&3 <<EOF
{
  "version": { "ref": "${VERSION}" },
  "metadata": [
    { "name": "file", "value": "${FILE}" },
    { "name": "commit", "value": "${COMMIT}" },
    { "name": "remote", "value": "${REMOTE}" },
    { "name": "trigger", "value": "${TRIGGER}" },
    { "name": "metadata", "value": "${METADATA}" }
  ]
}
EOF
